version: '3.8'

services:
  graph:
    image: martinmunilla/devtrivia_app
    environment:
      POSTGRES_HOST: 'postgresdb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_NAME: 'devtrivia'
      POSTGRES_PORT: '5432'
      REDIS_HOST: 'redisdb'
      FRONTEND_URL: ''
      SECRET: 'asdfassaqwmnrvzxupovuoiuyioyiuoadf'
    depends_on:
      - postgresdb
      - redisdb
    ports:
      - '4000:4000'

  postgresdb:
    image: martinmunilla/devtrivia_db

  redisdb:
    image: redis
    volumes:
      - devtrivia-redis:/data

volumes:
  devtrivia-redis:
    driver: local
